// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function map(a, f) {
  return a.then((function (aa) {
                return Promise.resolve(Curry._1(f, aa));
              }));
}

function bind(a, f) {
  return a.then(Curry.__1(f));
}

var Let_syntax = {
  map: map,
  bind: bind
};

var $$Promise$1 = {
  Let_syntax: Let_syntax
};

exports.$$Promise = $$Promise$1;
/* No side effect */
